name: app-env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - boto3
  - flask
  - flask-cors
  - hydrostats
  - natsort
  - netCDF4
  - pandas
  - requests
  - shapely
  - s3fs
  - xarray
  - uwsgi
  - xarray
  - zarr